apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: hello-python   # Este deve corresponder ao rótulo usado no seu deployment.yaml
  ports:
    - protocol: TCP
      port: 80   # A porta que deseja expor externamente
      targetPort: 5000   # A porta em que seu serviço Flask está escutando
